companies = {'Search for a company' : '',
'3M': 'MMM',
 'A. O. Smith': 'AOS',
 'Abbott Laboratories': 'ABT',
 'AbbVie': 'ABBV',
 'Abiomed': 'ABMD',
 'Accenture': 'ACN',
 'Activision Blizzard': 'ATVI',
 'ADM': 'ADM',
 'Adobe': 'ADBE',
 'Advance Auto Parts': 'AAP',
 'Advanced Micro Devices': 'AMD',
 'AES Corp': 'AES',
 'Aflac': 'AFL',
 'Agilent Technologies': 'A',
 'Air Products & Chemicals': 'APD',
 'Akamai Technologies': 'AKAM',
 'Alaska Air Group': 'ALK',
 'Albemarle Corporation': 'ALB',
 'Alexandria Real Estate Equities': 'ARE',
 'Align Technology': 'ALGN',
 'Allegion': 'ALLE',
 'Alliant Energy': 'LNT',
 'Allstate Corp': 'ALL',
 'Alphabet (Class A)': 'GOOGL',
 'Alphabet (Class C)': 'GOOG',
 'Altria Group': 'MO',
 'Amazon': 'AMZN',
 'Amcor': 'AMCR',
 'Ameren Corp': 'AEE',
 'American Airlines Group': 'AAL',
 'American Electric Power': 'AEP',
 'American Express': 'AXP',
 'American International Group': 'AIG',
 'American Tower': 'AMT',
 'American Water Works': 'AWK',
 'Ameriprise Financial': 'AMP',
 'AmerisourceBergen': 'ABC',
 'Ametek': 'AME',
 'Amgen': 'AMGN',
 'Amphenol Corp': 'APH',
 'Analog Devices': 'ADI',
 'Ansys': 'ANSS',
 'Anthem': 'ANTM',
 'Aon': 'AON',
 'APA Corporation': 'APA',
 'Apple': 'AAPL',
 'Applied Materials': 'AMAT',
 'Aptiv': 'APTV',
 'Arista Networks': 'ANET',
 'Arthur J. Gallagher & Co.': 'AJG',
 'Assurant': 'AIZ',
 'AT&T': 'T',
 'Atmos Energy': 'ATO',
 'Autodesk': 'ADSK',
 'Automatic Data Processing': 'ADP',
 'AutoZone': 'AZO',
 'AvalonBay Communities': 'AVB',
 'Avery Dennison': 'AVY',
 'Baker Hughes': 'BKR',
 'Ball Corp': 'BLL',
 'Bank of America': 'BAC',
 'Baxter International': 'BAX',
 'Becton Dickinson': 'BDX',
 'Berkshire Hathaway': 'BRK.B',
 'Best Buy': 'BBY',
 'Bio-Rad Laboratories': 'BIO',
 'Biogen': 'BIIB',
 'BlackRock': 'BLK',
 'BNY Mellon': 'BK',
 'Boeing Company': 'BA',
 'Booking Holdings': 'BKNG',
 'BorgWarner': 'BWA',
 'Boston Properties': 'BXP',
 'Boston Scientific': 'BSX',
 'Bristol-Myers Squibb': 'BMY',
 'Broadcom': 'AVGO',
 'Broadridge Financial Solutions': 'BR',
 'Brown–Forman': 'BF.B',
 'C. H. Robinson': 'CHRW',
 'Cabot Oil & Gas': 'COG',
 'Cadence Design Systems': 'CDNS',
 'Caesars Entertainment': 'CZR',
 'Campbell Soup': 'CPB',
 'Capital One Financial': 'COF',
 'Cardinal Health': 'CAH',
 'CarMax': 'KMX',
 'Carnival Corporation': 'CCL',
 'Carrier Global': 'CARR',
 'Catalent': 'CTLT',
 'Caterpillar': 'CAT',
 'Cboe Global Markets': 'CBOE',
 'CBRE': 'CBRE',
 'CDW': 'CDW',
 'Celanese': 'CE',
 'Centene Corporation': 'CNC',
 'CenterPoint Energy': 'CNP',
 'Cerner': 'CERN',
 'CF Industries': 'CF',
 'Charles River Laboratories': 'CRL',
 'Charles Schwab Corporation': 'SCHW',
 'Charter Communications': 'CHTR',
 'Chevron Corporation': 'CVX',
 'Chipotle Mexican Grill': 'CMG',
 'Chubb': 'CB',
 'Church & Dwight': 'CHD',
 'Cigna': 'CI',
 'Cincinnati Financial': 'CINF',
 'Cintas Corporation': 'CTAS',
 'Cisco Systems': 'CSCO',
 'Citigroup': 'C',
 'Citizens Financial Group': 'CFG',
 'Citrix Systems': 'CTXS',
 'Clorox': 'CLX',
 'CME Group': 'CME',
 'CMS Energy': 'CMS',
 'Coca-Cola Company': 'KO',
 'Cognizant Technology Solutions': 'CTSH',
 'Colgate-Palmolive': 'CL',
 'Comcast': 'CMCSA',
 'Comerica': 'CMA',
 'Conagra Brands': 'CAG',
 'ConocoPhillips': 'COP',
 'Consolidated Edison': 'ED',
 'Constellation Brands': 'STZ',
 'Copart': 'CPRT',
 'Corning': 'GLW',
 'Corteva': 'CTVA',
 'Costco': 'COST',
 'Crown Castle': 'CCI',
 'CSX': 'CSX',
 'Cummins': 'CMI',
 'CVS Health': 'CVS',
 'D. R. Horton': 'DHI',
 'Danaher Corporation': 'DHR',
 'Darden Restaurants': 'DRI',
 'DaVita': 'DVA',
 'Deere & Co.': 'DE',
 'Delta Air Lines': 'DAL',
 'Dentsply Sirona': 'XRAY',
 'Devon Energy': 'DVN',
 'DexCom': 'DXCM',
 'Diamondback Energy': 'FANG',
 'Digital Realty Trust': 'DLR',
 'Discover Financial Services': 'DFS',
 'Discovery (Series A)': 'DISCA',
 'Discovery (Series C)': 'DISCK',
 'Dish Network': 'DISH',
 'Dollar General': 'DG',
 'Dollar Tree': 'DLTR',
 'Dominion Energy': 'D',
 "Domino's Pizza": 'DPZ',
 'Dover Corporation': 'DOV',
 'Dow': 'DOW',
 'DTE Energy': 'DTE',
 'Duke Energy': 'DUK',
 'Duke Realty Corp': 'DRE',
 'DuPont': 'DD',
 'DXC Technology': 'DXC',
 'Eastman Chemical': 'EMN',
 'Eaton Corporation': 'ETN',
 'eBay': 'EBAY',
 'Ecolab': 'ECL',
 'Edison International': 'EIX',
 'Edwards Lifesciences': 'EW',
 'Electronic Arts': 'EA',
 'Eli Lilly & Co': 'LLY',
 'Emerson Electric Company': 'EMR',
 'Enphase Energy': 'ENPH',
 'Entergy': 'ETR',
 'EOG Resources': 'EOG',
 'Equifax': 'EFX',
 'Equinix': 'EQIX',
 'Equity Residential': 'EQR',
 'Essex Property Trust': 'ESS',
 'Estée Lauder Companies': 'EL',
 'Etsy': 'ETSY',
 'Everest Re': 'RE',
 'Evergy': 'EVRG',
 'Eversource Energy': 'ES',
 'Exelon': 'EXC',
 'Expedia Group': 'EXPE',
 'Expeditors': 'EXPD',
 'Extra Space Storage': 'EXR',
 'ExxonMobil': 'XOM',
 'F5 Networks': 'FFIV',
 'Facebook': 'FB',
 'Fastenal': 'FAST',
 'Federal Realty Investment Trust': 'FRT',
 'FedEx': 'FDX',
 'Fidelity National Information Services': 'FIS',
 'Fifth Third Bancorp': 'FITB',
 'First Republic Bank': 'FRC',
 'FirstEnergy': 'FE',
 'Fiserv': 'FISV',
 'Fleetcor': 'FLT',
 'FMC Corporation': 'FMC',
 'Ford': 'F',
 'Fortinet': 'FTNT',
 'Fortive': 'FTV',
 'Fortune Brands Home & Security': 'FBHS',
 'Fox Corporation (Class A)': 'FOXA',
 'Fox Corporation (Class B)': 'FOX',
 'Franklin Resources': 'BEN',
 'Freeport-McMoRan': 'FCX',
 'Gap': 'GPS',
 'Garmin': 'GRMN',
 'Gartner': 'IT',
 'Generac Holdings': 'GNRC',
 'General Dynamics': 'GD',
 'General Electric': 'GE',
 'General Mills': 'GIS',
 'General Motors': 'GM',
 'Genuine Parts': 'GPC',
 'Gilead Sciences': 'GILD',
 'Global Payments': 'GPN',
 'Globe Life': 'GL',
 'Goldman Sachs': 'GS',
 'Halliburton': 'HAL',
 'Hanesbrands': 'HBI',
 'Hasbro': 'HAS',
 'HCA Healthcare': 'HCA',
 'Healthpeak Properties': 'PEAK',
 'Henry Schein': 'HSIC',
 'Hess Corporation': 'HES',
 'Hewlett Packard Enterprise': 'HPE',
 'Hilton Worldwide': 'HLT',
 'Hologic': 'HOLX',
 'Home Depot': 'HD',
 'Honeywell': 'HON',
 'Hormel': 'HRL',
 'Host Hotels & Resorts': 'HST',
 'Howmet Aerospace': 'HWM',
 'HP': 'HPQ',
 'Humana': 'HUM',
 'Huntington Bancshares': 'HBAN',
 'Huntington Ingalls Industries': 'HII',
 'IBM': 'IBM',
 'IDEX Corporation': 'IEX',
 'Idexx Laboratories': 'IDXX',
 'IHS Markit': 'INFO',
 'Illinois Tool Works': 'ITW',
 'Illumina': 'ILMN',
 'Incyte': 'INCY',
 'Ingersoll Rand': 'IR',
 'Intel': 'INTC',
 'Intercontinental Exchange': 'ICE',
 'International Flavors & Fragrances': 'IFF',
 'International Paper': 'IP',
 'Interpublic Group': 'IPG',
 'Intuit': 'INTU',
 'Intuitive Surgical': 'ISRG',
 'Invesco': 'IVZ',
 'IPG Photonics': 'IPGP',
 'IQVIA': 'IQV',
 'Iron Mountain': 'IRM',
 'J. B. Hunt': 'JBHT',
 'Jack Henry & Associates': 'JKHY',
 'Jacobs Engineering Group': 'J',
 'JM Smucker': 'SJM',
 'Johnson & Johnson': 'JNJ',
 'Johnson Controls': 'JCI',
 'JPMorgan Chase': 'JPM',
 'Juniper Networks': 'JNPR',
 'Kansas City Southern': 'KSU',
 "Kellogg's": 'K',
 'KeyCorp': 'KEY',
 'Keysight Technologies': 'KEYS',
 'Kimberly-Clark': 'KMB',
 'Kimco Realty': 'KIM',
 'Kinder Morgan': 'KMI',
 'KLA Corporation': 'KLAC',
 'Kraft Heinz': 'KHC',
 'Kroger': 'KR',
 'L Brands': 'LB',
 'L3Harris Technologies': 'LHX',
 'LabCorp': 'LH',
 'Lam Research': 'LRCX',
 'Lamb Weston': 'LW',
 'Las Vegas Sands': 'LVS',
 'Leggett & Platt': 'LEG',
 'Leidos': 'LDOS',
 'Lennar': 'LEN',
 'Lincoln National': 'LNC',
 'Linde': 'LIN',
 'Live Nation Entertainment': 'LYV',
 'LKQ Corporation': 'LKQ',
 'Lockheed Martin': 'LMT',
 'Loews Corporation': 'L',
 "Lowe's": 'LOW',
 'Lumen Technologies': 'LUMN',
 'LyondellBasell': 'LYB',
 'M&T Bank': 'MTB',
 'Marathon Oil': 'MRO',
 'Marathon Petroleum': 'MPC',
 'MarketAxess': 'MKTX',
 'Marriott International': 'MAR',
 'Marsh & McLennan': 'MMC',
 'Martin Marietta Materials': 'MLM',
 'Masco': 'MAS',
 'Mastercard': 'MA',
 'Maxim Integrated': 'MXIM',
 'McCormick & Company': 'MKC',
 "McDonald's": 'MCD',
 'McKesson Corporation': 'MCK',
 'Medtronic': 'MDT',
 'Merck & Co.': 'MRK',
 'MetLife': 'MET',
 'Mettler Toledo': 'MTD',
 'MGM Resorts International': 'MGM',
 'Microchip Technology': 'MCHP',
 'Micron Technology': 'MU',
 'Microsoft': 'MSFT',
 'Mid-America Apartments': 'MAA',
 'Moderna': 'MRNA',
 'Mohawk Industries': 'MHK',
 'Molson Coors Beverage Company': 'TAP',
 'Mondelez International': 'MDLZ',
 'Monolithic Power Systems': 'MPWR',
 'Monster Beverage': 'MNST',
 "Moody's Corporation": 'MCO',
 'Morgan Stanley': 'MS',
 'Motorola Solutions': 'MSI',
 'MSCI': 'MSCI',
 'Nasdaq': 'NDAQ',
 'NetApp': 'NTAP',
 'Netflix': 'NFLX',
 'Newell Brands': 'NWL',
 'Newmont': 'NEM',
 'News Corp (Class A)': 'NWSA',
 'News Corp (Class B)': 'NWS',
 'NextEra Energy': 'NEE',
 'Nielsen Holdings': 'NLSN',
 'Nike': 'NKE',
 'NiSource': 'NI',
 'Norfolk Southern': 'NSC',
 'Northern Trust': 'NTRS',
 'Northrop Grumman': 'NOC',
 'NortonLifeLock': 'NLOK',
 'Norwegian Cruise Line Holdings': 'NCLH',
 'Nov': 'NOV',
 'NRG Energy': 'NRG',
 'Nucor': 'NUE',
 'Nvidia': 'NVDA',
 'NVR': 'NVR',
 'NXP': 'NXPI',
 "O'Reilly Automotive": 'ORLY',
 'Occidental Petroleum': 'OXY',
 'Old Dominion Freight Line': 'ODFL',
 'Omnicom Group': 'OMC',
 'Oneok': 'OKE',
 'Oracle': 'ORCL',
 'Organon & Co.': 'OGN',
 'Otis Worldwide': 'OTIS',
 'Paccar': 'PCAR',
 'Packaging Corporation of America': 'PKG',
 'Parker-Hannifin': 'PH',
 'Paychex': 'PAYX',
 'Paycom': 'PAYC',
 'PayPal': 'PYPL',
 'Penn National Gaming': 'PENN',
 'Pentair': 'PNR',
 "People's United Financial": 'PBCT',
 'PepsiCo': 'PEP',
 'PerkinElmer': 'PKI',
 'Perrigo': 'PRGO',
 'Pfizer': 'PFE',
 'Philip Morris International': 'PM',
 'Phillips 66': 'PSX',
 'Pinnacle West Capital': 'PNW',
 'Pioneer Natural Resources': 'PXD',
 'PNC Financial Services': 'PNC',
 'Pool Corporation': 'POOL',
 'PPG Industries': 'PPG',
 'PPL': 'PPL',
 'Principal Financial Group': 'PFG',
 'Procter & Gamble': 'PG',
 'Progressive Corporation': 'PGR',
 'Prologis': 'PLD',
 'Prudential Financial': 'PRU',
 'PTC': 'PTC',
 'Public Service Enterprise Group': 'PEG',
 'Public Storage': 'PSA',
 'PulteGroup': 'PHM',
 'PVH': 'PVH',
 'Qorvo': 'QRVO',
 'Qualcomm': 'QCOM',
 'Quanta Services': 'PWR',
 'Quest Diagnostics': 'DGX',
 'Ralph Lauren Corporation': 'RL',
 'Raymond James Financial': 'RJF',
 'Raytheon Technologies': 'RTX',
 'Realty Income Corporation': 'O',
 'Regency Centers': 'REG',
 'Regeneron Pharmaceuticals': 'REGN',
 'Regions Financial Corporation': 'RF',
 'Republic Services': 'RSG',
 'ResMed': 'RMD',
 'Robert Half International': 'RHI',
 'Rockwell Automation': 'ROK',
 'Rollins': 'ROL',
 'Roper Technologies': 'ROP',
 'Ross Stores': 'ROST',
 'Royal Caribbean Group': 'RCL',
 'S&P Global': 'SPGI',
 'Salesforce': 'CRM',
 'SBA Communications': 'SBAC',
 'Schlumberger': 'SLB',
 'Seagate Technology': 'STX',
 'Sealed Air': 'SEE',
 'Sempra Energy': 'SRE',
 'ServiceNow': 'NOW',
 'Sherwin-Williams': 'SHW',
 'Simon Property Group': 'SPG',
 'Skyworks Solutions': 'SWKS',
 'Snap-on': 'SNA',
 'Southern Company': 'SO',
 'Southwest Airlines': 'LUV',
 'Stanley Black & Decker': 'SWK',
 'Starbucks': 'SBUX',
 'State Street Corporation': 'STT',
 'Steris': 'STE',
 'Stryker Corporation': 'SYK',
 'SVB Financial': 'SIVB',
 'Synchrony Financial': 'SYF',
 'Synopsys': 'SNPS',
 'Sysco': 'SYY',
 'T-Mobile US': 'TMUS',
 'T. Rowe Price': 'TROW',
 'Take-Two Interactive': 'TTWO',
 'Tapestry': 'TPR',
 'Target Corporation': 'TGT',
 'TE Connectivity': 'TEL',
 'Teledyne Technologies': 'TDY',
 'Teleflex': 'TFX',
 'Teradyne': 'TER',
 'Tesla': 'TSLA',
 'Texas Instruments': 'TXN',
 'Textron': 'TXT',
 'The Cooper Companies': 'COO',
 'The Hartford': 'HIG',
 'The Hershey Company': 'HSY',
 'The Mosaic Company': 'MOS',
 'The Travelers Companies': 'TRV',
 'The Walt Disney Company': 'DIS',
 'Thermo Fisher Scientific': 'TMO',
 'TJX Companies': 'TJX',
 'Tractor Supply Company': 'TSCO',
 'Trane Technologies': 'TT',
 'TransDigm Group': 'TDG',
 'Trimble': 'TRMB',
 'Truist Financial': 'TFC',
 'Twitter': 'TWTR',
 'Tyler Technologies': 'TYL',
 'Tyson Foods': 'TSN',
 'U.S. Bancorp': 'USB',
 'UDR': 'UDR',
 'Ulta Beauty': 'ULTA',
 'Under Armour (Class A)': 'UAA',
 'Under Armour (Class C)': 'UA',
 'Union Pacific': 'UNP',
 'United Airlines': 'UAL',
 'United Parcel Service': 'UPS',
 'United Rentals': 'URI',
 'UnitedHealth Group': 'UNH',
 'Universal Health Services': 'UHS',
 'Unum Group': 'UNM',
 'Valero Energy': 'VLO',
 'Ventas': 'VTR',
 'Verisign': 'VRSN',
 'Verisk Analytics': 'VRSK',
 'Verizon Communications': 'VZ',
 'Vertex Pharmaceuticals': 'VRTX',
 'VF Corporation': 'VFC',
 'ViacomCBS': 'VIAC',
 'Viatris': 'VTRS',
 'Visa': 'V',
 'Vornado Realty Trust': 'VNO',
 'Vulcan Materials': 'VMC',
 'W. R. Berkley Corporation': 'WRB',
 'W. W. Grainger': 'GWW',
 'Wabtec': 'WAB',
 'Walgreens Boots Alliance': 'WBA',
 'Walmart': 'WMT',
 'Waste Management': 'WM',
 'Waters Corporation': 'WAT',
 'WEC Energy Group': 'WEC',
 'Wells Fargo': 'WFC',
 'Welltower': 'WELL',
 'West Pharmaceutical Services': 'WST',
 'Western Digital': 'WDC',
 'Western Union': 'WU',
 'WestRock': 'WRK',
 'Weyerhaeuser': 'WY',
 'Whirlpool Corporation': 'WHR',
 'Williams Companies': 'WMB',
 'Willis Towers Watson': 'WLTW',
 'Wynn Resorts': 'WYNN',
 'Xcel Energy': 'XEL',
 'Xilinx': 'XLNX',
 'Xylem': 'XYL',
 'Yum! Brands': 'YUM',
 'Zebra Technologies': 'ZBRA',
 'Zimmer Biomet': 'ZBH',
 'Zions Bancorp': 'ZION',
 'Zoetis': 'ZTS'}
